### ISSUE TITLE
instagrapi 1.5.1

### ISSUE THREAD

**Issue by OneFrenchLeft** [mishalshanavas/notes-bot#1]
ERROR: Cannot install instagrapi==1.5.1 and requests==2.26.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested requests==2.26.0
    instagrapi 1.5.1 depends on requests==2.25.1

**Comment by mishalshanavas** [comment]
Just install the latest version of instagrapi it would work fine :)

(sorry for being late)
